version: "3"

services: 
  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    depends_on: 
      - mongo
      - api
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on: 
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jamm3e3333
      - MONGO_INITDB_ROOT_PASSWORD=ahoj123
